-- Создание таблиц для базы данных store

-- Таблица product - хранит информацию о продуктах
CREATE TABLE IF NOT EXISTS product (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    picture_url varchar(255)
);

-- Таблица product_info - хранит дополнительную информацию о продуктах
CREATE TABLE IF NOT EXISTS product_info (
    product_id bigint NOT NULL,
    name varchar(255) NOT NULL,
    price double precision
);

-- Таблица orders - хранит информацию о заказах
CREATE TABLE IF NOT EXISTS orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    status varchar(255)
);

-- Таблица orders_date - хранит информацию о датах заказов
CREATE TABLE IF NOT EXISTS orders_date (
    order_id bigint NOT NULL,
    status varchar(255),
    date_created date DEFAULT current_date
);

-- Таблица order_product - связывает заказы и продукты
CREATE TABLE IF NOT EXISTS order_product (
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL
); 