CREATE TABLE product(
    id bigint generated by default as identity, 
    name varchar(255) not null, 
    picture_url varchar(255)
);

COMMENT ON TABLE product IS 'Stores data about sausages: the identifier, the name and the link to the picture';

CREATE TABLE product_info(
    product_id bigint not null, 
    name varchar(255) not null, 
    price double precision
);

COMMENT ON TABLE product_info IS 'Stores data about sausages: identifier, name and price';

CREATE TABLE orders(
    id bigint generated by default as identity,
    status varchar(255)
);

COMMENT ON TABLE orders IS 'Stores information about orders: the order ID and status.';

CREATE TABLE orders_date(
    order_id bigint not null,
    status varchar(255),
    date_created date default current_date
);

COMMENT ON TABLE orders_date IS 'Stores information about orders: the order ID, date and time, and its status';

CREATE TABLE order_product(
    quantity integer not null,
    order_id bigint not null,
    product_id bigint not null
);

COMMENT ON TABLE order_product IS 'Stores information about which sausages were included in the order: the order ID and the sausage ID';